### PR TITLE
Add support for `NextHop` schema

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9dSUE8Ok7WZG7Y_tK:-Mr9dSUE8Ok7WZG7Y_tL:b-trmyy2) (no related file):*
need to update stringification

---

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792#-:-Mr9fByE3R7aRuzd1x9L:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

___
*[pybatfish/datamodel/route.py, line 234 at r4](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9e_rC1JDKGLXk5-xF:-Mr9e_rD1N2rNZvfG8I_:bwklcna) ([raw file](https://github.com/batfish/pybatfish/blob/14a1cfc5b1c184a48c4a7678c392dbc7021bf156/pybatfish/datamodel/route.py#L234)):*
> ```Python
>     def from_dict(cls, json_dict: Dict) -> "NextHop":
>         if "type" not in json_dict:
>             raise ValueError("Missing type")
> ```

More verbose?

`f'Unknown type of NextHop, missing the `type` property: {json_dict}'`

for example.



_Code quote:_
```Python
se ValueError("Missing type")
```
___
*[pybatfish/datamodel/route.py, line 247 at r4](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9eqqiD0pOOwg2wmb0:-Mr9eqqiD0pOOwg2wmb1:blj6rpd) ([raw file](https://github.com/batfish/pybatfish/blob/14a1cfc5b1c184a48c4a7678c392dbc7021bf156/pybatfish/datamodel/route.py#L247)):*
> ```Python
>             return NextHopVtep.from_dict(json_dict)
>         else:
>             raise ValueError("Invalid type")
> ```

include the value? and maybe also the dict.

I'd probably also call it `Unhandled` instead of `Invalid`

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: all files reviewed, 4 unresolved discussions (waiting on @arifogel, @corinaminer, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9jj1N8utm3jl-hYpx:-Mr9jj1N8utm3jl-hYpy:b-aaexjp) (no related file):*
screwed up with a rebase. don't review for now.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @corinaminer, @dhalperi, and @sfraint)

___
*[pybatfish/datamodel/route.py, line 234 at r4](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9e_rC1JDKGLXk5-xF:-Mr9retrDEE_cB0TsYdM:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/14a1cfc5b1c184a48c4a7678c392dbc7021bf156/pybatfish/datamodel/route.py#L234)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

More verbose?

`f'Unknown type of NextHop, missing the `type` property: {json_dict}'`

for example.
</blockquote></details>

done
___
*[pybatfish/datamodel/route.py, line 247 at r4](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9eqqiD0pOOwg2wmb0:-Mr9rfRb-1Tb7koDMvTC:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/14a1cfc5b1c184a48c4a7678c392dbc7021bf156/pybatfish/datamodel/route.py#L247)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

include the value? and maybe also the dict.

I'd probably also call it `Unhandled` instead of `Invalid`
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9twmCEzzQWDc5dvMl:-Mr9twmDDTJ86CPL6qJA:bt6j8ly) (no related file):*
formatting in jupyter is messed up. debugging..

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/792#-Mr9twmCEzzQWDc5dvMl:-Mr9xUWD38Pkn4ut-REJ:b-1alzil) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

formatting in jupyter is messed up. debugging..
</blockquote></details>

never mind, didn't properly restart jupyter after fixing

---

**Comment by arifogel** [comment]
Sample notebook output:
image

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/792#-MrASS25Drk0QG4FHoAy:-MrASS25Drk0QG4FHoAz:b-5awf2m) (no related file):*
CI failure at r7 is due to batfish bug fixed in https://github.com/batfish/batfish/pull/7834

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer and @sfraint)

**Pull request merged**
