### PR TITLE
Upload init info

### PR DESCRIPTION
**Pull request by sfraint**
Add Pybatfish command to fetch, anonymize, and upload init info answers (parse status, parse warnings, conversion warnings for now).

### CODE REVIEW

**Comment by progwriter** [comment]
___
*[pybatfish/client/commands.py, line 77 at r1](https://reviewable.io/reviews/batfish/pybatfish/217#-LSuORuq1G80yyX8LhSn:-LSuRfOR9sxDNUM_ZzRu:bgpz16e) ([raw file](https://github.com/batfish/pybatfish/blob/c1a71c91dbe51d11627b1bb49a6d3a0081e03eff/pybatfish/client/commands.py#L77)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> _INIT_INFO_QUESTIONS = [
>     QuestionBase({
>         "class": "org.batfish.question.initialization.ParseWarningQuestion",
>         "differential": False,
>         "instance": {
>             "instanceName": "__parseWarning",
>         }
>     }),
>     QuestionBase({
>         "class": "org.batfish.question.initialization.FileParseStatusQuestion",
>         "differential": False,
>         "instance": {
>             "instanceName": "__fileParseStatus",
>         }
>     }),
>     QuestionBase({
>         "class": "org.batfish.question.initialization.ConversionWarningQuestion",
>         "differential": False,
>         "instance": {
>             "instanceName": "__viConversionWarning",
>         }
>     }),
> ]
> ```

Why does all this logic belong in `commands.py`?

My instinct is to move all logic related to this functionality into a library that is tested, and have the functions in `commands.py` be shallow wrappers for the lib.

Does that line up, @progwriter ? Any examples to follow?
</blockquote></details>

Definitely need to be split. I don't think a whole separate library is necessary, but a separate package/module would definitely be good for a lot of this functionality. `commands` should really only contain user-facing code.

**Comment by dhalperi** [comment]
___
*[pybatfish/client/commands.py, line 77 at r1](https://reviewable.io/reviews/batfish/pybatfish/217#-LSuORuq1G80yyX8LhSn:-LSuVaxO8zTi-QMdxhqN:bhntgou) ([raw file](https://github.com/batfish/pybatfish/blob/c1a71c91dbe51d11627b1bb49a6d3a0081e03eff/pybatfish/client/commands.py#L77)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

Definitely need to be split. I don't think a whole separate library is necessary, but a separate package/module would definitely be good for a lot of this functionality. `commands` should really only contain user-facing code.
</blockquote></details>

I guess I meant module. My parseltongue is week.

**Comment by progwriter** [comment]
___
*[pybatfish/client/commands.py, line 739 at r1](https://reviewable.io/reviews/batfish/pybatfish/217#-LSuUnkI2ENsr0GHBGd1:-LSx39khAKlPlWcVubnX:bqgh9bh) ([raw file](https://github.com/batfish/pybatfish/blob/c1a71c91dbe51d11627b1bb49a6d3a0081e03eff/pybatfish/client/commands.py#L739)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

So...`TemporaryDirectory` was added in python 3 and `mkdtemp` doesn't work with contexts.

Is it better in this case to use `mkdtemp` in a `try` & `finally` to mimic the cleanup done in contexts? or something else entirely?
</blockquote></details>

yeah, try .. finally is i a good call. 
Man, I'm tired of supporting legacy python :P

**Comment by dhalperi** [comment]
:ship: :clown_face:

**Pull request merged**
