### PR TITLE
Backwards compatibility for legacy RoutingStepDetail

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/808)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/808#-Ms2JPMP8vl5vM9p0uzF:-Ms2JPMQBBjq0WJJM0vJ:b8cp224) (no related file):*
Waiting on https://buildkite.com/intentionet/open-source-docker-pipeline/builds/1162

---
*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/808#-Ms2LCBaAqNu2zBJouGf:-Ms2LCBb2CbqpNQl70Y7:b-c4qbqg) (no related file):*
Regarding notebook changes:
Somewhere in the notebook output we are printing default attr string of `RouteInfo` and `RoutingStepDetail`, despite them having `__str__()` overrides.

Consider this new notebook excerpt (newlines added for legibility:
```
RouteInfo(protocol='static',
 network='0.0.0.0/0',
 nextHop=NextHopIp(ip='10.30.1.1', type='ip'),
 nextHopIp=None, # <-- this field is new from this PR
 admin=1,
 metric=0)
```

Note the new `nextHopIp` legacy field, which is set to `None` for non-legacy `RouteInfo`. 

Not sure why our notebook output has default attr string for `RouteInfo`, but ignoring for now as out of scope.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/808)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/808#-Ms2LCBaAqNu2zBJouGf:-Ms2MbreEbjWhXcEy3UY:bve0laf) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Regarding notebook changes:
Somewhere in the notebook output we are printing default attr string of `RouteInfo` and `RoutingStepDetail`, despite them having `__str__()` overrides.

Consider this new notebook excerpt (newlines added for legibility:
```
RouteInfo(protocol='static',
 network='0.0.0.0/0',
 nextHop=NextHopIp(ip='10.30.1.1', type='ip'),
 nextHopIp=None, # <-- this field is new from this PR
 admin=1,
 metric=0)
```

Note the new `nextHopIp` legacy field, which is set to `None` for non-legacy `RouteInfo`. 

Not sure why our notebook output has default attr string for `RouteInfo`, but ignoring for now as out of scope.
</blockquote></details>

Hypothesis: default attr string of enclosing class does not represent its attr-based member fields using their `__str__()` functions (at least if those members are themselves attr-based).

---

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
