### PR TITLE
Update notebooks after banning next hop 0.0.0.0

### PR DESCRIPTION
**Pull request by corinaminer**
Follow-up to batfish/batfish#7056.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/738)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer)

___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 829 at r1](https://reviewable.io/reviews/batfish/pybatfish/738#-MbmxxuNAooP6d18KnvI:-MbmxxuNAooP6d18KnvJ:b-sxecjn) ([raw file](https://github.com/batfish/pybatfish/blob/f0b612a182af0a003e322886dd02eacd2ba5c0a6/jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb#L829)):*
> ```
>        "    <tr>\n",
>        "      <th>6</th>\n",
>        "      <td>seattle</td>\n",
> ```

it looks like the paths have changed in this network. Need to revisit the text and make sure it lines up.
___
*[jupyter_notebooks/Introduction to Route Analysis.ipynb, line 452 at r1](https://reviewable.io/reviews/batfish/pybatfish/738#-Mbmy5U55FBsQuDDvuxw:-Mbmy5U55FBsQuDDvuxx:b-9h6zyr) ([raw file](https://github.com/batfish/pybatfish/blob/6b2fdb6a6225ed68d2b4b550db247627db08624a/jupyter_notebooks/Introduction to Route Analysis.ipynb#L452)):*
> ```
>        "    </tr>\n",
>        "    <tr>\n",
>        "      <th>253</th>\n",
> ```

Conformation: you checked the prose next to each changed block and ensured it's up to date?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/738)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 829 at r1](https://reviewable.io/reviews/batfish/pybatfish/738#-MbmxxuNAooP6d18KnvI:-MbmyXHU7_C80civ1OO8:bb1cf76) ([raw file](https://github.com/batfish/pybatfish/blob/f0b612a182af0a003e322886dd02eacd2ba5c0a6/jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb#L829)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

it looks like the paths have changed in this network. Need to revisit the text and make sure it lines up.
</blockquote></details>

This is the same route that shows up as a "new" route a few lines down. The only difference is the next hop IP went from 0.0.0.0 to AUTO/NONE(-1l), which is expected after the Batfish change.

Other changes are all just from the order of the results changing.
___
*[jupyter_notebooks/Introduction to Route Analysis.ipynb, line 452 at r1](https://reviewable.io/reviews/batfish/pybatfish/738#-Mbmy5U55FBsQuDDvuxw:-MbmzFSM3kzLigzXWzNz:b-vsetd9) ([raw file](https://github.com/batfish/pybatfish/blob/6b2fdb6a6225ed68d2b4b550db247627db08624a/jupyter_notebooks/Introduction to Route Analysis.ipynb#L452)):*
> the prose next to each changed block

not sure exactly what you mean. I assumed the row numbers changed due to an ordering change in the overall result

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/738)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[docs/source/notebooks/routingTables.ipynb, line 682 at r2](https://reviewable.io/reviews/batfish/pybatfish/738#-Mbn3xK5A2bOWiB7CcqY:-Mbn3xK6DJPzZh-btiq_:bsd6tzv) ([raw file](https://github.com/batfish/pybatfish/blob/d0e6f4f32a6f78c6c2bcb769fc4c171fb77d00a1/docs/source/notebooks/routingTables.ipynb#L682)):*
> ```
>        "Originator_Id                2.1.1.2\n",
>        "Cluster_List                    None\n",
>        "Tag                             None\n",
> ```

fyi, this section fundamentally changed because the cell is `result.iloc[0]`, and the first result is now a different route. (perhaps unfortunate that the example is now an aggregate instead of a BGP route, though. Could do `iloc[1]` if you think it's better to show BGP)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/738)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[jupyter_notebooks/Introduction to Route Analysis.ipynb, line 452 at r1](https://reviewable.io/reviews/batfish/pybatfish/738#-Mbmy5U55FBsQuDDvuxw:-Mbn8NjQDhOGGbhR4e5D:b-j97eb9) ([raw file](https://github.com/batfish/pybatfish/blob/6b2fdb6a6225ed68d2b4b550db247627db08624a/jupyter_notebooks/Introduction to Route Analysis.ipynb#L452)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

> the prose next to each changed block

not sure exactly what you mean. I assumed the row numbers changed due to an ordering change in the overall result
</blockquote></details>

All I meant is, the notebook doesn't say something like "You can see 50 routes in this table, look at row 11 and you get this..."

Because if it did, then we might need to update that text.

**Pull request merged**
