### PR TITLE
Routingpolicy docs

### PR DESCRIPTION
**Pull request by ratulm**
Document the two route policies questions. 

Needed small changes to convert_schema question because `bgpRoutes` scheme is somewhat special.

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
Looks like some of Todd's changes crept in. Did you try rebasing?

> Reviewed 2 of 7 files at r2, 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/667#-:-MIVs6leABUaxmtDhTll:bfjke0p)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein and @ratulm)

___
*[docs/nb_gen/schema.py, line 13 at r3](https://reviewable.io/reviews/batfish/pybatfish/667#-MIVrrL4ETD7v190NRo3:-MIVrpxG0e9qwuVigfGW:b1pb38b) ([raw file](https://github.com/batfish/pybatfish/blob/8c8492e0bda69cb511fc579c40f7ca051723e16e/docs/nb_gen/schema.py#L13)):*
> ```
> "str": "str",
> ```
why do we need to add this?

**Review by ratulm — COMMENTED** [review]
None of Todd's changes should be included. The diff with master should only be relevant to documenting those two questions (which I double checked). i'll squash and merge to make the master commit history ok. 

rebasing is advanced operation for me :)  if you prefer rebasing, let me know and I'll go learn a new trick. 

> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/667#-:-MIVtO5m5VoPq4E9xn8r:b-5ne66b)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[docs/nb_gen/schema.py, line 13 at r3](https://reviewable.io/reviews/batfish/pybatfish/667#-MIVrrL4ETD7v190NRo3:-MIVtuKMDE4nhn62sbdK:b-opwf25) ([raw file](https://github.com/batfish/pybatfish/blob/8c8492e0bda69cb511fc579c40f7ca051723e16e/docs/nb_gen/schema.py#L13)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

> ```
> "str": "str",
> ```
why do we need to add this?
</blockquote></details>

I made convert_schema (more) recursive for code simplicity, which meant that things that were on the value side of the map can appear as the input to the function.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/667)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[docs/nb_gen/schema.py, line 13 at r3](https://reviewable.io/reviews/batfish/pybatfish/667#-MIVrrL4ETD7v190NRo3:-MIVuNIsCwvnAGtlwW0o:b-yg4hs0) ([raw file](https://github.com/batfish/pybatfish/blob/8c8492e0bda69cb511fc579c40f7ca051723e16e/docs/nb_gen/schema.py#L13)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I made convert_schema (more) recursive for code simplicity, which meant that things that were on the value side of the map can appear as the input to the function. 
</blockquote></details>

The other way to handle is to special case its treatment.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/667)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[docs/nb_gen/schema.py, line 13 at r3](https://reviewable.io/reviews/batfish/pybatfish/667#-MIVrrL4ETD7v190NRo3:-MIVuYWe8vFzgPBUYNBN:b-be7rj5) ([raw file](https://github.com/batfish/pybatfish/blob/8c8492e0bda69cb511fc579c40f7ca051723e16e/docs/nb_gen/schema.py#L13)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

The other way to handle is to special case its treatment. 
</blockquote></details>

hmm....let me just do that to keep the meaning of the map clean.

**Comment by ratulm** [comment]
need more fixes.

**Pull request closed without merging**
