### PR TITLE
Test on only newer versions

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/669)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/integration/test_network_funcs.py, line 218 at r2](https://reviewable.io/reviews/batfish/pybatfish/669#-MIQDtnq2Tb7Vo58eTEw:-MIQDtnq2Tb7Vo58eTEx:bf985nv) ([raw file](https://github.com/batfish/pybatfish/blob/8833e975dcfd8d548efe8348db70f8d724e62cc3/tests/integration/test_network_funcs.py#L218)):*
> ```
> __auto_complete_tester
> ```
fyi: not necessary to preface helpers with `__`, as long as they don't start with `test` pytest will assume they're helpers / not test functions

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/669)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/669)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[tests/integration/test_network_funcs.py, line 218 at r4](https://reviewable.io/reviews/batfish/pybatfish/669#-MIQfhdiAwgK9CluAwTW:-MIQfhdiAwgK9CluAwTX:b-eueba) ([raw file](https://github.com/batfish/pybatfish/blob/1a5fad888295e2b86e904e7d0f99d1d6b79f3605/tests/integration/test_network_funcs.py#L218)):*
> ```Python
> 
> 
> def auto_complete_tester(session, completion_types):
> ```

this parameter is unused because auto_complete does not exist for sessions.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/669)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[tests/integration/test_network_funcs.py, line 218 at r4](https://reviewable.io/reviews/batfish/pybatfish/669#-MIQfhdiAwgK9CluAwTW:-MIQg2_53wMfVERi5Tte:b-1sz8es) ([raw file](https://github.com/batfish/pybatfish/blob/1a5fad888295e2b86e904e7d0f99d1d6b79f3605/tests/integration/test_network_funcs.py#L218)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

this parameter is unused because auto_complete does not exist for sessions. 
</blockquote></details>

ps: followed the pattern of other tests in this file.

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/669)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
