### PR TITLE
pybatfish: delete legacy default session

### PR DESCRIPTION
**Pull request by dhalperi**
It's been long enough that we can delete bf_session, bf_q, and the like.
This is now leading to confusion as folks who customize the sessions
are surprised when the default session is used instead.

This is a breaking change:

1. Add missing helpers for network_object to session
2. Delete command and extended commands files.
Commands is the one that contained the default bf_session.
3. Fixup some other code and tests to use real sessions, also
adding some missing or wrong type annotations as they
messed me up.
4. Delete bfq also, but keep the docs working. Fix a few old
incorrect references. (e.g., to documentation paths that
are no longer there.)

---

**Stack**:
- #911
- #910
- #909
- #907 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/907)* status: 0 of 16 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/907#-O-yjXfy0E-pkgfP09Gn:-O-yjXfy0E-pkgfP09Go:b-nq5y2v) (no related file):*
I need to fix up the docs still.

___

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/907)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @progwriter and @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/907#-O05CyRw9tB_L7lZen_w:-O05CyRw9tB_L7lZen_x:bafjvi3) (no related file):*
FYI I tested the doc changes by adding saving of the built does to the build process. You can look at the `Build docs` step on master and on this PR and compare them. It looks right to me.

___

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/907)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @progwriter and @ratulm)

___
*[`docs/source/specifiers.md` line 202 at r2](https://reviewable.io/reviews/batfish/pybatfish/907#-O05D8Kc6sTzPs5qvaNx:-O05D8Kc6sTzPs5qvaNy:bl8v36m) ([raw file](https://github.com/batfish/pybatfish/blob/2fd847a830045f14e7eae1317869a2423831510d/docs/source/specifiers.md#L202)):*
> ```Markdown
> ### Disposition Specifier
> 
> Flow dispositions are used in questions like [reachability](https://pybatfish.readthedocs.io/en/latest/notebooks/forwarding.html#Reachability) to identify flow outcomes. The disposition specifier takes as input a comma-separated list of disposition values, which are interpreted using logical OR.
> ```

FYI I don't believe this URL has worked in a long time...

**Review by progwriter — COMMENTED** [review]
👏🤩:lgtm: 

> Reviewed 15 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/907#-:-O05Uk933W4-1VBprETb:b4vti0i)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
