### PR TITLE
Pandas examples notebook

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ratulm and @saparikh)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/837#-N3RVbIE6D1wrSIaeqF1:-N3RVbIE6D1wrSIaeqF2:b-tyt9af) (no related file):*
Will tal after review cycle completes. We talked a bit in person about some possibilities.

___

**Review by saparikh — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by saparikh — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837#-:-N3V_1R64M9Wy4Ghxlk8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: all files reviewed, 14 unresolved discussions (waiting on @ratulm)

___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 14 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VdbHo9JyEJ_0ZtaOZ:-N3VdbHo9JyEJ_0ZtaO_:b-n20c93) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L14)):*
> ```
>    "metadata": {},
>    "source": [
>     "Batfish questions can return a huge amount of data, which you may want to filter in various ways based on your task. While most Batfish questions support basic filtering, they may not support your desired filtering criteria. Further, for performance, you may want to fetch the answer once and filter it using multiple different criteria. These scenarios are where Pandas-based filtering can help. \n",
> ```

Are you only going to do simple filtering? Not groupby or other things?
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 14 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VddqT8Bb_Bv02400F:-N3VddqT8Bb_Bv02400G:b-lh5il0) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L14)):*
> ```
>    "metadata": {},
>    "source": [
>     "Batfish questions can return a huge amount of data, which you may want to filter in various ways based on your task. While most Batfish questions support basic filtering, they may not support your desired filtering criteria. Further, for performance, you may want to fetch the answer once and filter it using multiple different criteria. These scenarios are where Pandas-based filtering can help. \n",
> ```

I believe you need a little extra work to make sure your examples work on empty dataframes. Take a look at some of my internal notebooks.
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 81 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbCMW7Mz-nFN5UxYl:-N3VbCMW7Mz-nFN5UxYm:b-vwy8ra) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L81)):*
> ```
>    "metadata": {},
>    "source": [
>     "After initializing the snapshot, you often want to look at the initIssues answer. If there are too many issues, you may want to ignore a particular class of issues. We show below how to do that. "
> ```

code font, link to read the docs.



_Code quote:_
```
 initIssues
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 299 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3Vbjz7EPyOm2gcg3d5:-N3Vbjz7EPyOm2gcg3d6:b-c1a6j) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L299)):*
> ```
>     "\n",
>     "issues[issues.apply(\n",
>     "                lambda row: all([row['Line_Text'] is None or \n",
> ```

here and below, suggest factoring out the lambda as a function. Users get screwed up when they have to build complicated lambdas inline, and they can't reuse. May as well demonstrate good patterns.
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 299 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbzHED9_QJ-FVcon2:-N3VbzHED9_QJ-FVcon3:beuny2n) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L299)):*
> ```
>     "\n",
>     "issues[issues.apply(\n",
>     "                lambda row: all([row['Line_Text'] is None or \n",
> ```

simpler would be `foo not in row.get("Line_Text", "")` or whatever.



_Code quote:_
```
row['Line_Text'] is None 
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 299 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VcGCh9ugbGU1w2yXE:-N3VcGCh9ugbGU1w2yXF:b-umtcae) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L299)):*
> ```
>     "\n",
>     "issues[issues.apply(\n",
>     "                lambda row: all([row['Line_Text'] is None or \n",
> ```

suggest running a reformatter on this code? Python style is that `or` goes on next line.



_Code quote:_
```
or 
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 300 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbZ1iC7Ve9frq4oXp:-N3VbZ1iC7Ve9frq4oXq:b-yw33c1) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L300)):*
> ```
>     "issues[issues.apply(\n",
>     "                lambda row: all([row['Line_Text'] is None or \n",
>     "                                 line_text not in row['Line_Text'] for line_text in ignore_line_texts]), \n",
> ```

remove the `[]` -- all takes a generator and this actually makes it materialize a list first



_Code quote:_
```
    "                lambda row: all([row['Line_Text'] is None or \n",
    "                                 line_text not in row['Line_Text'] for line_text in ignore_line_texts]), \n",
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 308 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbKAPCXgK-kXKSVLY:-N3VbKAPCXgK-kXKSVLZ:b-y45kub) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L308)):*
> ```
>    "metadata": {},
>    "source": [
>     "In the code above, we are using [Pandas's apply method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) to map rows in the `issues` DataFrame to a binary array. A row maps to True if its `Line_Text` is `None` or does not contain any of the substrings in the `ignoredDetails` list. The Python method [all()](https://docs.python.org/3/library/functions.html#all) returns `True` if all elements of the input iterable are `True`. Using the binary array as a filter for `issues` produces rows that match our criterion. "
> ```

code font



_Code quote:_
```
apply 
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 308 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbMJ-A4J51LUPX4da:-N3VbMJ-A4J51LUPX4db:b-zgdnkf) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L308)):*
> ```
>    "metadata": {},
>    "source": [
>     "In the code above, we are using [Pandas's apply method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) to map rows in the `issues` DataFrame to a binary array. A row maps to True if its `Line_Text` is `None` or does not contain any of the substrings in the `ignoredDetails` list. The Python method [all()](https://docs.python.org/3/library/functions.html#all) returns `True` if all elements of the input iterable are `True`. Using the binary array as a filter for `issues` produces rows that match our criterion. "
> ```

earlier you call it `Dataframe`. Pick one and be consistent?

(FWIW, I think Pandas uses `DataFrame`).



_Code quote:_
```
DataFram
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 308 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VbUhH8OuYgFqD9XJ6:-N3VbUhH8OuYgFqD9XJ7:b-y45kub) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L308)):*
> ```
>    "metadata": {},
>    "source": [
>     "In the code above, we are using [Pandas's apply method](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html) to map rows in the `issues` DataFrame to a binary array. A row maps to True if its `Line_Text` is `None` or does not contain any of the substrings in the `ignoredDetails` list. The Python method [all()](https://docs.python.org/3/library/functions.html#all) returns `True` if all elements of the input iterable are `True`. Using the binary array as a filter for `issues` produces rows that match our criterion. "
> ```

code font



_Code quote:_
```
True
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 409 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VcdIJAxyvHp4aPYxE:-N3VcdIJAxyvHp4aPYxF:b-8zofi) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L409)):*
> ```
>    "metadata": {},
>    "source": [
>     "The code above is similar to the one we used earlier. The main difference is the use of Python method [any()](https://docs.python.org/3/library/functions.html#any) that returns `True` if any element of the input iterable is `True`."
> ```

huh? the main difference is `in` instead of `not in`.

would be a lot clearer with reusable code.

Seems like you should also handle `None` here even if it didn't come up in the example.



_Code quote:_
```
he main difference is the use of Python method [any()](https://docs.python.org/3/library/functions.html#any) that returns `True` if any element of the input iterable is `True
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 776 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3Vd1It87nvRi6Az8Cs:-N3Vd1It87nvRi6Az8Ct:bxk0nuz) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L776)):*
> ```
>    "metadata": {},
>    "source": [
>     "To filter based on a column, we need to know its data type. We can learn that in the [batfish documentation](https://pybatfish.readthedocs.io/en/latest/questions.html) or using Python's `type()` method:"
> ```

this is not guaranteed to work for most things. E.g., BgpRouteDiff or whatever will not have a concrete type.

It will also not work for List[T] even if T is known.



_Code quote:_
```
ed on a column, we need to know its data type. We can learn that in the [batfish documentation](https://pybatfish.readthedocs.io/en/latest/questions.html) or
```
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 776 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VdVtLBS_LuLCP3EwQ:-N3VdVtLBS_LuLCP3EwR:b1h23t1) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L776)):*
> ```
>    "metadata": {},
>    "source": [
>     "To filter based on a column, we need to know its data type. We can learn that in the [batfish documentation](https://pybatfish.readthedocs.io/en/latest/questions.html) or using Python's `type()` method:"
> ```

proper noun



_Code quote:_
```
batfish 
```

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @ratulm)

___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 14 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VdbHo9JyEJ_0ZtaOZ:-N3Vz_YQ9_WMTmZDKqnr:bbtnvz9) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Are you only going to do simple filtering? Not groupby or other things?
</blockquote></details>

Can you suggest a good example for group by (either here or athttps://docs.google.com/document/d/1POMf6xjkHItZPFGo1qV33HXl59-1-iM-8VP86pHx8Wk/edit#) ? 

Is this good: Count interfaces per node? 
___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 14 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VddqT8Bb_Bv02400F:-N3W5Xfq3IG5VCoAJfBx:b-nh0dsw) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

I believe you need a little extra work to make sure your examples work on empty dataframes. Take a look at some of my internal notebooks.
</blockquote></details>

I removed the `type` example. Are there others that won't work?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[`jupyter_notebooks/Pandas Examples.ipynb` line 14 at r3](https://reviewable.io/reviews/batfish/pybatfish/837#-N3VddqT8Bb_Bv02400F:-N3aIka_67MtFkq--p3v:bxk2aiq) ([raw file](https://github.com/batfish/pybatfish/blob/6a74aec6d1cb88901b3dd791c78a512494d11e09/jupyter_notebooks/Pandas%20Examples.ipynb#L14)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Found the issue I've run into: https://stackoverflow.com/questions/19990182/calling-apply-on-an-empty-pandas-dataframe and necessitates `result_type='reduce'` when creating a new column. I guess you're not doing that here?
</blockquote></details>

no, I am not.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/837)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
