### PR TITLE
Remove recommonmark from docs environment

### PR DESCRIPTION
**Pull request by ratulm**
This one builds fine on RTD

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/729)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[docs/requirements.txt, line 6 at r2](https://reviewable.io/reviews/batfish/pybatfish/729#-MY7OQBi45yF2y835uKD:-MY7OQBjDyqjqI__uZwW:bxalcsg) ([raw file](https://github.com/batfish/pybatfish/blob/d59d01c05ef0344acff055c5e8e90e22f0b5c955/docs/requirements.txt#L6)):*
> ```vimhelp
> nbsphinx==0.5.0
> progressbar2==3.47.0
> recommonmark # must not be pinned because https://github.com/readthedocs/readthedocs.org/issues/8096
> ```

RTD doesn't use this file, I don't think this is necessary.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/729)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[docs/requirements.txt, line 6 at r2](https://reviewable.io/reviews/batfish/pybatfish/729#-MY7OQBi45yF2y835uKD:-MY7Q-I36xXx3ZW_QKEe:b-m3mual) ([raw file](https://github.com/batfish/pybatfish/blob/d59d01c05ef0344acff055c5e8e90e22f0b5c955/docs/requirements.txt#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

RTD doesn't use this file, I don't think this is necessary.
</blockquote></details>

Would it not help keep local doc builds in line with RTD builds?

**Comment by dhalperi** [comment]
___
*[docs/requirements.txt, line 6 at r2](https://reviewable.io/reviews/batfish/pybatfish/729#-MY7OQBi45yF2y835uKD:-MY7QRSs9_ckvOIZ4kgD:b-lbd61m) ([raw file](https://github.com/batfish/pybatfish/blob/d59d01c05ef0344acff055c5e8e90e22f0b5c955/docs/requirements.txt#L6)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Would it not help keep local doc builds in line with RTD builds?
</blockquote></details>

Don't we *need* this for local builds? Is it a transitive dependency of something else in the file? (I didn't think it was)

**Comment by dhalperi** [comment]
___
*[docs/requirements.txt, line 6 at r2](https://reviewable.io/reviews/batfish/pybatfish/729#-MY7OQBi45yF2y835uKD:-MY7Qim-7xMV8PBPFNAJ:bwwn7x6) ([raw file](https://github.com/batfish/pybatfish/blob/d59d01c05ef0344acff055c5e8e90e22f0b5c955/docs/requirements.txt#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Don't we *need* this for local builds? Is it a transitive dependency of something else in the file? (I didn't think it was)
</blockquote></details>

Anyway, certainly the comment is wrong.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/729)* status: 1 of 2 files reviewed, all discussions resolved

___
*[docs/requirements.txt, line 6 at r2](https://reviewable.io/reviews/batfish/pybatfish/729#-MY7OQBi45yF2y835uKD:-MY7RKe68bHE8BB2RUZt:b-wi939p) ([raw file](https://github.com/batfish/pybatfish/blob/d59d01c05ef0344acff055c5e8e90e22f0b5c955/docs/requirements.txt#L6)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Anyway, certainly the comment is wrong.
</blockquote></details>

OK, maybe it is not important to keep these two in sync. What we do locally (questions to notebooks) is different from what happens at RTD.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/729)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
