### PR TITLE
Force keyword arguments in question constructor

### LINKED ISSUE #222: Error out on default parameters
pybatfish lets me ask `bfq.nodeProperties("garbage")` and returns an answer happily. It should instead produce an error.

### PR DESCRIPTION
**Pull request by progwriter**
Reject positional arguments in question constructors.

Fixes #222

### CODE REVIEW

**Comment by dhalperi** [comment]
___
*[pybatfish/question/question.py, line 79 at r1](https://reviewable.io/reviews/batfish/pybatfish/244#-LUkr_ijAalfcAD-bVhX:-LUkr_ijAalfcAD-bVhY:b-c7dete) ([raw file](https://github.com/batfish/pybatfish/blob/2942edf8a9e7b4bdee82378ad2ef16380d41a885/pybatfish/question/question.py#L79)):*
> ```
> *args, 
> ```

why even include `*args` here?

**Comment by dhalperi** [comment]
___
*[pybatfish/question/question.py, line 83 at r1](https://reviewable.io/reviews/batfish/pybatfish/244#-LUkrgco1t-B9SqBIOlg:-LUkrgco1t-B9SqBIOlh:b-i935ti) ([raw file](https://github.com/batfish/pybatfish/blob/2942edf8a9e7b4bdee82378ad2ef16380d41a885/pybatfish/question/question.py#L83)):*
> ```Python
>             # Reject positional args; this way is PY2-compliant
>             if args:
>                 raise TypeError("Please use keyword arguments")
> ```

Is there a better error message that helps the user do the right next thing?

**Comment by progwriter** [comment]
___
*[pybatfish/question/question.py, line 79 at r1](https://reviewable.io/reviews/batfish/pybatfish/244#-LUkr_ijAalfcAD-bVhX:-LUlTWMqCDDrQQuU273F:b-p1b5md) ([raw file](https://github.com/batfish/pybatfish/blob/2942edf8a9e7b4bdee82378ad2ef16380d41a885/pybatfish/question/question.py#L79)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> *args, 
> ```

why even include `*args` here?
</blockquote></details>

With bare asterisk you get syntax error

**Comment by progwriter** [comment]
___
*[pybatfish/question/question.py, line 83 at r1](https://reviewable.io/reviews/batfish/pybatfish/244#-LUkrgco1t-B9SqBIOlg:-LUlTZ542sSOmAuuQ16_:b26kplr) ([raw file](https://github.com/batfish/pybatfish/blob/2942edf8a9e7b4bdee82378ad2ef16380d41a885/pybatfish/question/question.py#L83)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Is there a better error message that helps the user do the right next thing?
</blockquote></details>

What do you have in mind? The default Py3 message (if we used bare `*`) is absolutely horrible: "expected 1 positional argument, received X`

**Pull request merged**
