### PR TITLE
Notebooks: Update after Batfish nexthop changes

### PR DESCRIPTION
**Pull request by sfraint**
Update notebooks after Batfish nexthop changes in https://github.com/batfish/batfish/pull/7028

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/736)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[docs/source/notebooks/routingTables.ipynb, line 50 at r1](https://reviewable.io/reviews/batfish/pybatfish/736#-MapWsc66YztB3WTYBJi:-MapWsc66YztB3WTYBJj:b1vbe44) ([raw file](https://github.com/batfish/pybatfish/blob/a42ef51198bb0a4fd918c62faccdf0c2d9dfaeff/docs/source/notebooks/routingTables.ipynb#L50)):*
> ```
>    "id": "ef262854",
> ```
not sure where these `id` lines came from, but they're not interfering with validating the notebook

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/736)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @arifogel)

___
*[docs/source/notebooks/routingTables.ipynb, line 50 at r1](https://reviewable.io/reviews/batfish/pybatfish/736#-MapWsc66YztB3WTYBJi:-MapbI8CBQyAX8EccCko:b4r4s8n) ([raw file](https://github.com/batfish/pybatfish/blob/a42ef51198bb0a4fd918c62faccdf0c2d9dfaeff/docs/source/notebooks/routingTables.ipynb#L50)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>    "id": "ef262854",
> ```
not sure where these `id` lines came from, but they're not interfering with validating the notebook
</blockquote></details>

manually removed for now

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/736)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[docs/source/notebooks/routingTables.ipynb, line 50 at r1](https://reviewable.io/reviews/batfish/pybatfish/736#-MapVzXWBRvi1b296GKF:-MapVzXXEd4Hea62DDzP:b6zqby7) ([raw file](https://github.com/batfish/pybatfish/blob/a42ef51198bb0a4fd918c62faccdf0c2d9dfaeff/docs/source/notebooks/routingTables.ipynb#L50)):*
> ```
>   {
>    "cell_type": "markdown",
>    "id": "ef262854",
> ```

can you remove the `"id"` entries?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/736)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[docs/source/notebooks/routingTables.ipynb, line 50 at r1](https://reviewable.io/reviews/batfish/pybatfish/736#-MapVzXWBRvi1b296GKF:-MapcLzB4u7y6jvgiJMh:b-55iaup) ([raw file](https://github.com/batfish/pybatfish/blob/a42ef51198bb0a4fd918c62faccdf0c2d9dfaeff/docs/source/notebooks/routingTables.ipynb#L50)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

can you remove the `"id"` entries?
</blockquote></details>

ignore stale comment

**Pull request merged**
