### PR TITLE
Coordinator Errors: Fail fast when retrying

### PR DESCRIPTION
**Pull request by sfraint**
Instead of retrying for many minutes on coordinator failures, stop after 3 retries (after ~5.6 seconds).

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/668)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/668#-MIKezq_87_kMVOe6m56:-MIKezq_87_kMVOe6m57:b-fhoevx) (no related file):*
More changes coming, to have better behavior for both initial connection and for something where coordinator may actually go unresponsive for some time (e.g. during GC)

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/668)* status: 0 of 13 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/668#-MIKezq_87_kMVOe6m56:-MIMngBL5hQt9bLbo8UT:b-d9reu5) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

More changes coming, to have better behavior for both initial connection and for something where coordinator may actually go unresponsive for some time (e.g. during GC)
</blockquote></details>

Updated `Session` to check coordinator connection by default (using get version) - this check fails fast with a newly added request session (with different retry settings).

Other API calls still use the old-style request session (with lots of retries).

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/668)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/668#-MIRBKeG5kn-JL0mgDw-:-MIRBKeHEqluktbjFooT:b-fzfve4) (no related file):*
Like we chatted about @progwriter , I will back out the use of get version to trigger fast-failing and instead attach it to question loading

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/668)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @progwriter)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/668#-MIRBKeG5kn-JL0mgDw-:-MIVDC4VEJKQLW8E8bKo:bddvn6u) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Like we chatted about @progwriter , I will back out the use of get version to trigger fast-failing and instead attach it to question loading
</blockquote></details>

Ok, updated

---

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 14 files at r2, 4 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/668)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
