### PR TITLE
Fix RFC1918 space

### PR DESCRIPTION
**Pull request by Antonio-Prado**
172.16.0.0/12

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/861#-:-NENJzih8ooGfjAN4qG4:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Antonio-Prado)

**Comment by Antonio-Prado** [comment]
> Thanks!

are you going to commit?

**Comment by dhalperi** [comment]
Tests aren't passing

**Comment by Antonio-Prado** [comment]
> Tests aren't passing

I see, is there anything else I can do with the tests?

**Comment by dhalperi** [comment]
Hi @Antonio-Prado - yes, please re-generate the notebooks so that the tests pass.

**Comment by Antonio-Prado** [comment]
> Hi @Antonio-Prado - yes, please re-generate the notebooks so that the tests pass.

hi, how can I re-generate the notebooks?
thank you

**Comment by dhalperi** [comment]
Hi @Antonio-Prado - I had to fix the router configs to update the PLs to match the corrected RFC definition. If this passes, I will merge.

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/861)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Antonio-Prado)

**Pull request merged**
