### PR TITLE
Notebook Testing: add ability to skip tests for old versions

### PR DESCRIPTION
**Pull request by sfraint**
Add ability to skip notebook tests for older versions of Batfish or Pybatfish.

Useful for new notebooks exercising new functionality not in older versions.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/683)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[tests/common_util.py, line 71 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfQ-o63mTQeN3N1y7q:-MIfQ-o63mTQeN3N1y7r:b-92smbu) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/common_util.py#L71)):*
> ```Python
> def get_bf_version(session):
>     """Get BF version."""
>     # Use env var as version number if specified (get around some backends having dev version number)
> ```

What's the need here? Dev version number should just be treated as MAX_VERSION?
___
*[tests/integration/test_notebook.py, line 56 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfPi1w1b5hY-0xGQLP:-MIfPi1w1b5hY-0xGQLQ:b4vxh14) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/integration/test_notebook.py#L56)):*
> ```
> def session():
> ```
get the version here, pass the version around instead of `session`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/683)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[tests/common_util.py, line 59 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfQRq0CpTte-6JS03z:-MIfQRq1-EWUh1dXLN4N:b-b61n87) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/common_util.py#L59)):*
> ```Python
>     print("min_version, bf_version: {}, {}".format(min_version, bf_version))
>     if _version_less_than(_version_to_tuple(bf_version), min_version_tuple):
>         print("BF version too low")
> ```

removing these
___
*[tests/common_util.py, line 71 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfQ-o63mTQeN3N1y7q:-MIfQIfr9Lx7CxY0tT05:b8njmpo) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/common_util.py#L71)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

What's the need here? Dev version number should just be treated as MAX_VERSION?
</blockquote></details>

today, we're (incorrectly) using dev version for all containers
___
*[tests/integration/test_notebook.py, line 56 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfPi1w1b5hY-0xGQLP:-MIfQNNX36IsDElvfPf7:b-d7bhn0) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/integration/test_notebook.py#L56)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> def session():
> ```
get the version here, pass the version around instead of `session`.
</blockquote></details>

will do

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/683)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

___
*[tests/common_util.py, line 71 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfQ-o63mTQeN3N1y7q:-MIfVRb_-X_kART3x73f:b-grff1c) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/common_util.py#L71)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

today, we're (incorrectly) using dev version for all containers
</blockquote></details>

(after https://github.com/batfish/docker/pull/65, new containers should have the right version numbers)
___
*[tests/integration/test_notebook.py, line 56 at r2](https://reviewable.io/reviews/batfish/pybatfish/683#-MIfPi1w1b5hY-0xGQLP:-MIfVHvp4VVo8ocDMT4k:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/282fffbf2a0493feb4abe628e6ad4797b0247ea2/tests/integration/test_notebook.py#L56)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

will do
</blockquote></details>

done

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/683)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
