### PR TITLE
Path analysis

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by saparikh** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9L7Bo3sLTUG_hGMlo:-LM9eNA-2FgBCvzxgtRX:b7j6svq) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

A couple of other things to think about beyond comments below:

1/ Talk about the ignoreAcls flag in traceroute? (Should this flag be renamed ignoreFilters now for consistent terminology?)

2/ Include an example of inside to outside flow as well? I believe all examples are for the other direction. 
</blockquote></details>

For 1) we should change the flag to `ignoreFilters` for consistency. If we can find a good example to use in the network, we should add that as part of the narrative.

2) I don't think we need an inside to outside example, unless there is a specific type of issue we cannot showcase without it 

---

**Comment by saparikh** [comment]
___
*[jupyter_notebooks/Introduction to Path Analysis.ipynb, line 363 at r1](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9IarM5xcx6kwv4Dl1:-LM9f-a95YtyBCa1Z3hx:bs04kdy) ([raw file](https://github.com/batfish/pybatfish/blob/c6291590bf93f87a17a9d0603b641653e2bc63ab/jupyter_notebooks/Introduction to Path Analysis.ipynb#L363)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Call this "Comprehensive reachability analysis"? 
</blockquote></details>

That makes sense. Either Comprehensive or something similar. Basically, we want to distinguish the use-case for reachability from traceroute. 

The explanation for traceroute is simple:
Traceroute is to be used when you have a concrete flow in mind (flow doesn't need to be a full 5-tuple). 

The explanation for reachability needs to be fleshed out.
Reachability is to be used when you want to do ???

**Comment by saparikh** [comment]
___
*[jupyter_notebooks/Introduction to Path Analysis.ipynb, line 379 at r1](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9IwNb1yaUUMAmALe3:-LM9fhV4BzfWgr8R914x:b-c6m62) ([raw file](https://github.com/batfish/pybatfish/blob/c6291590bf93f87a17a9d0603b641653e2bc63ab/jupyter_notebooks/Introduction to Path Analysis.ipynb#L379)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Alternative pivot from traceroute to reachability:

Traceroute finds paths taken by the specified flow through the network, which is useful in analyzing connectivity for that flow.  

Batfish also enables more comprehensive reachability analysis that can provide guarantees for all possible flows between multiple sources and destinations and using any header within the specified header space (e.g., src and destination addresses and ports). This capability is very powerful when you want to ensure network security and reliability."

</blockquote></details>

I think if we replace `abstract` with `comprehensive` or the appropriate term from above, then that should be fine. The detailed explanation can leave the impression that it is difficult to use.

**Comment by saparikh** [comment]
___
*[jupyter_notebooks/Introduction to Path Analysis.ipynb, line 841 at r1](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9KZgmCKIORtWJrX0P:-LM9g48WBNHQt2w-LLO3:b-352itz) ([raw file](https://github.com/batfish/pybatfish/blob/c6291590bf93f87a17a9d0603b641653e2bc63ab/jupyter_notebooks/Introduction to Path Analysis.ipynb#L841)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

by "your network" you mean AS2? (that should be made clear.)

also, do you need the `enter` keyword in your query. 
</blockquote></details>

Yes, we should change network to AS2.

I believe you have to have `enter` keyword in the query for the start location, but not 100% sure. You definitely need it in the `dstIp` specifier

**Comment by saparikh** [comment]
___
*[jupyter_notebooks/Introduction to Path Analysis.ipynb, line 841 at r1](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9KZgmCKIORtWJrX0P:-LM9gNb3AqIKZ9PbAHj3:b1tk6h3) ([raw file](https://github.com/batfish/pybatfish/blob/c6291590bf93f87a17a9d0603b641653e2bc63ab/jupyter_notebooks/Introduction to Path Analysis.ipynb#L841)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

Yes, we should change network to AS2.

I believe you have to have `enter` keyword in the query for the start location, but not 100% sure. You definitely need it in the `dstIp` specifier
</blockquote></details>

My understanding is that `enter` keyword in the start location will ensure that the input filter for each interface that the query will pick as the origination point of the flow will be processed.

**Comment by saparikh** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/94#-LM9L7Bo3sLTUG_hGMlo:-LMDcac89HqzesNWEgwk:bm7n9vl) (no related file):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

1. Example could be around debugging routing alone without worrying about filters

2. The issue is basically: Can all of your internal hosts reach the outside world? Maybe I am wrong, but the set of current examples seem like variants of the same basic pattern. I was hoping for some diversity since reachability is such as a diverse question. One can think of three types of flows: outside to internal hosts, outside to internal routers, internal hosts to outside and have examples of each. Another way to add some color is to use way-pointing. 
</blockquote></details>

We need to keep this first notebook on path analysis simple. We can do a separate notebook just on reachability and look at the other scenarios. Keeping the narrative focused on one flow (outside to inside) keeps everything streamlined and easy for the user to follow.

---

**Comment by progwriter** [comment]
Closing in favor of updated #152

**Pull request closed without merging**
