### PR TITLE
Do not start Batfish WorkMgrV1 for regular integration tests

### PR DESCRIPTION
**Pull request by arifogel**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/853#-N9n03Ih-cbNhl2aFtdU:-N9n03Ih-cbNhl2aFtdV:b-xwdeiq) (no related file):*
after batfish/batfish#8489

___

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[`.buildkite/integration_tests.sh` line 8 at r2](https://reviewable.io/reviews/batfish/pybatfish/853#-N9nHofy7_l0K2eEPGGO:-N9nHofy7_l0K2eEPGGP:bi7xhxv) ([raw file](https://github.com/batfish/pybatfish/blob/56a38dc5b03c11e68376d8e76a98cf580deb7c02/.buildkite/integration_tests.sh#L8)):*
> ```Shell
> 
> shift
> # remaining args are extra coordinator args
> ```

move this down near the new bit?



_Code quote:_
```Shell
shift
# remaining args are extra coordinator args
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[`.buildkite/integration_tests.sh` line 8 at r2](https://reviewable.io/reviews/batfish/pybatfish/853#-N9nHofy7_l0K2eEPGGO:-N9nIYet0OeXhdIxd82J:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/56a38dc5b03c11e68376d8e76a98cf580deb7c02/.buildkite/integration_tests.sh#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

move this down near the new bit?
</blockquote></details>

done

**Review by arifogel — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @arifogel, @dhalperi, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
