### PR TITLE
Update notebooks with tunnel encapsulation attr column

### PR DESCRIPTION
**Pull request by corinaminer**
After batfish/batfish#8359.

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/840)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @corinaminer and @dhalperi)

___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 703 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YGcH9V3EZxZJQzGr:-N44YGcH9V3EZxZJQzGs:b-8z51k7) ([raw file](https://github.com/batfish/pybatfish/blob/d02c2b1d7c5c0371ae6650523dfca0e88e1671dc/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L703)):*
> ```
>        "    <tr>\n",
>        "      <th>0</th>\n",
>        "      <td>losangeles</td>\n",
> ```

Have you reviewed the changes to this notebook to confirm that the story and accompanying text are correct?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/840)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @corinaminer and @dhalperi)

___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 1413 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YZT237GWTuG4LMOM:-N44YZT237GWTuG4LMON:b4fmwza) ([raw file](https://github.com/batfish/pybatfish/blob/013586bb0742956929b6086e549cac879a8ac445/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L1413)):*
> ```
>        "\n",
>        "   Reference_Tunnel_Encapsulation_Attribute Snapshot_Weight Reference_Weight  \\\n",
>        "0                                      None            None             None   \n",
> ```

It seems weird this is `` instead of `None`. Why aren't we getting the "empty" value?

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/840)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dhalperi)

___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 703 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YGcH9V3EZxZJQzGr:-N44apVED1K9K3cmm2tI:b-hs4xyq) ([raw file](https://github.com/batfish/pybatfish/blob/d02c2b1d7c5c0371ae6650523dfca0e88e1671dc/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L703)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

Have you reviewed the changes to this notebook to confirm that the story and accompanying text are correct?
</blockquote></details>

Yes -- the routes output is unchanged except for order and the new column, and the story still makes sense to the same degree it did before.
___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 1413 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YZT237GWTuG4LMOM:-N44ae6h-7uL8sCmuG0G:b-kncmqd) ([raw file](https://github.com/batfish/pybatfish/blob/013586bb0742956929b6086e549cac879a8ac445/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L1413)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

It seems weird this is `` instead of `None`. Why aren't we getting the "empty" value?
</blockquote></details>

are you talking about the tunnel encap attribute? That column is populated with `None` (little hard to see in this diff since the column is so wide)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/840)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corinaminer)

___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 703 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YGcH9V3EZxZJQzGr:-N44d6b5CkQ8qgRhdHMu:b-7eklps) ([raw file](https://github.com/batfish/pybatfish/blob/d02c2b1d7c5c0371ae6650523dfca0e88e1671dc/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L703)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Yes -- the routes output is unchanged except for order and the new column, and the story still makes sense to the same degree it did before.
</blockquote></details>

Ack, thank you!
___
*[`jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb` line 1413 at r1](https://reviewable.io/reviews/batfish/pybatfish/840#-N44YZT237GWTuG4LMOM:-N44dE3026qZVyHdaLWA:b-7eklps) ([raw file](https://github.com/batfish/pybatfish/blob/013586bb0742956929b6086e549cac879a8ac445/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L1413)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

are you talking about the tunnel encap attribute? That column is populated with `None` (little hard to see in this diff since the column is so wide)
</blockquote></details>

Ack, thank you!

**Pull request merged**
