### PR TITLE
linking videos from the readme

### PR DESCRIPTION
**Pull request by millstein**
I also rewrote the list of Batfish capabilities somewhat, to line up better with the videos.

### CODE REVIEW

**Comment by ratulm** [comment]
These look good to me but the main landing page (and README) that we are shooting for is the Batfish one. (Nothing is externally linking to the pybatfish github page.) You certainly want to push such changes there and then copy over what we end up with here.

Please add @saparikh as approver. He recently re-did the README.

**Comment by saparikh** [comment]
___
*[README.md, line 31 at r2](https://reviewable.io/reviews/batfish/pybatfish/214#-LSVyExg9I9EhzCHJxpy:-LSVyExg9I9EhzCHJxpz:b-6wvnr) ([raw file](https://github.com/batfish/pybatfish/blob/b389a0c5ede4dbe06331da68859eb7c82401f5bf/README.md#L31)):*
> ```Markdown
> ## What kinds of correctness checks does Batfish support?
> 
> Batfish makes it easy to explore and validate a wide range of network behaviors and device configuration attributes, for example:
> ```

I wouldn't worry about re-wording this section to line up with the videos. The original text flows with the overall message we have. `provide correctness guarantees` is meant to tie in with the first paragraph, telling the reader what behaviours and attributes we can guarantee correctness for.

**Comment by saparikh** [comment]
___
*[README.md, line 34 at r2](https://reviewable.io/reviews/batfish/pybatfish/214#-LSVyjNQB0utSJfthoqs:-LSVyjNQB0utSJfthoqt:btqlpcv) ([raw file](https://github.com/batfish/pybatfish/blob/b389a0c5ede4dbe06331da68859eb7c82401f5bf/README.md#L34)):*
> ```Markdown
> #### Configuration Compliance
> * Flag undefined-but-referenced or defined-but-unreferenced structures (e.g., ACLs, route maps)
> * Validate configuration settings for MTUs, AAA, NTP, logging, etc. [[video](https://www.youtube.com/watch?v=qOXRaVs1Uz4)]
> ```

I am not a big fan of linking each video back to the README page. For bullet points that do not have a video link, it can leave the reader with the impression that we don't have that capability yet. Also, not all of the videos we do will map to a specific bullet point here.

**Comment by saparikh** [comment]
___
*[README.md, line 38 at r2](https://reviewable.io/reviews/batfish/pybatfish/214#-LSVz9P59JMQwdNeMT8q:-LSVz9P59JMQwdNeMT8r:b-b98e0e) ([raw file](https://github.com/batfish/pybatfish/blob/b389a0c5ede4dbe06331da68859eb7c82401f5bf/README.md#L38)):*
> ```Markdown
> #### Security and Availability Validation
> * ACLs and firewalls block all and only disallowed traffic [[video](https://youtu.be/KixQYEDh33s)]
> * Compute and compare the routes learned by each node [[video](https://www.youtube.com/watch?v=AutkFa0xUxg)]
> ```

Route comparison is not related to correctness guarantees

**Comment by saparikh** [comment]
I am fine with the link to the Getting Started Video, but the rest of the changes should be reverted. We don't want to create any coupling between the bullet points here and the videos, since not everything will line up perfectly (and we will have videos that are not represented in these bullet points).

Better solution is to link to the YouTube channel, so when the user clicks on it they will see all of the available videos.

**Comment by millstein** [comment]
@saparikh How is this version, which addresses your earlier comments?

**Pull request merged**
