### PR TITLE
add docs for routing policy questions

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/676)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @anothermattbrown and @millstein)

**Review by anothermattbrown — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/676)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @millstein)

**Review by anothermattbrown — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/676)* status: all files reviewed, 1 unresolved discussion (waiting on @millstein and @ratulm)

___
*[docs/source/notebooks/routingTables.ipynb, line 616 at r1](https://reviewable.io/reviews/batfish/pybatfish/676#-MIWWBhP8B-cgkHCPuyJ:-MIWWBhQET3xrwaHRGwX:b-n6rjhv) ([raw file](https://github.com/batfish/pybatfish/blob/9acaa069866bbc10225bfa953501e796ef30f3d1/docs/source/notebooks/routingTables.ipynb#L616)):*
> ```
>    ]
>   },
>   {
> ```

why did this get removed?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/676)* status: all files reviewed, 1 unresolved discussion (waiting on @anothermattbrown and @millstein)

___
*[docs/source/notebooks/routingTables.ipynb, line 616 at r1](https://reviewable.io/reviews/batfish/pybatfish/676#-MIWWBhP8B-cgkHCPuyJ:-MIWZPb119IShNGLRQvW:bpnyoe2) ([raw file](https://github.com/batfish/pybatfish/blob/9acaa069866bbc10225bfa953501e796ef30f3d1/docs/source/notebooks/routingTables.ipynb#L616)):*
<details><summary><i>Previously, anothermattbrown (Matt Brown) wrote…</i></summary><blockquote>

why did this get removed?
</blockquote></details>

I believe because we removed the prefixTracer question.

**Pull request merged**
