### PR TITLE
Update tests and notebooks after batfish/batfish#7939

### PR DESCRIPTION
**Pull request by arifogel**
- updates following batfish/batfish#7939
- admin down interfaces on vendors that disconnect admin down interfaces now appear as blacklisted
- update expected facts
- update notebooks for new properties and blacklist value change

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/813#-MtVM8zr63J-XhJZK7gf:-MtVM8zsCtzLXiP3NJaN:b-xwdxx3) (no related file):*
after batfish/batfish#7939

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[docs/source/notebooks/configProperties.ipynb, line 900 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoCqag1as2tZWh8XAi:-MtoCqag1as2tZWh8XAj:b-s79c0o) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/docs/source/notebooks/configProperties.ipynb#L900)):*
> ```
>        "HSRP_Groups                                            []\n",
>        "HSRP_Version                                         None\n",
>        "Inactive_Reason                     Administratively down\n",
> ```

how come i don't see this added to the results table?
___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 225 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoFDdu6SXPJHyzNInf:-MtoFDdu6SXPJHyzNIng:bdb1t2s) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L225)):*
> ```
>       "text/html": [
>        "<style  type=\"text/css\" >\n",
>        "#T_pybfstylerow0_col0,#T_pybfstylerow0_col1,#T_pybfstylerow0_col2,#T_pybfstylerow0_col3,#T_pybfstylerow0_col4,#T_pybfstylerow1_col0,#T_pybfstylerow1_col1,#T_pybfstylerow1_col2,#T_pybfstylerow1_col3,#T_pybfstylerow1_col4,#T_pybfstylerow2_col0,#T_pybfstylerow2_col1,#T_pybfstylerow2_col2,#T_pybfstylerow2_col3,#T_pybfstylerow2_col4,#T_pybfstylerow3_col0,#T_pybfstylerow3_col1,#T_pybfstylerow3_col2,#T_pybfstylerow3_col3,#T_pybfstylerow3_col4{\n",
> ```

Looks like differential reachability is now including a flow starting on a node that is failed on the base snapshot. That's not something we want, is it? Can you look into why this is happening? Maybe the diff reach answerer has weird logic for picking start locations, or maybe forkSnapshot with `deactivate_nodes` isn't having the right effect.

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 314 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoIZrb1jykf516MyA5:-MtoIZrb1jykf516MyA6:b-xgmnk3) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L314)):*
> ```
>    "metadata": {},
>    "source": [
>     "We see from the result that the failures of `London` would in fact permit a flow that was originally being blocked by the `AS1_TO_AS2` ACL on `New York`. This difference reveals a potential security vulnerability! Luckily, Batfish allows us to catch and fix it before something bad happens in production. Similarly, if there were flows that were carried in `BASE_SNAPSHOT_NAME` but dropped in `FAIL_LONDON_SNAPSHOT_NAME` (an availability issue), Batfish would have caught it.  \n",
> ```

yeah as corina identifies, if this part of the NB changes we need to make sure the prose is accurate.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[docs/source/notebooks/configProperties.ipynb, line 900 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoCqag1as2tZWh8XAi:-MtoIskb7hwlmLTgowNK:b-4yut20) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/docs/source/notebooks/configProperties.ipynb#L900)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

how come i don't see this added to the results table?
</blockquote></details>

Note the ellipsis. This field is in the truncated middle of the results.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 314 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoIZrb1jykf516MyA5:-MtoXVfwCWYpdiYGC_00:b-xjfikm) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L314)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

yeah as corina identifies, if this part of the NB changes we need to make sure the prose is accurate.
</blockquote></details>

it's not inaccurate per se, though it might be worth addressing what the first result is since it's not demonstrating the point the notebook is trying to make. But I think the bigger question is why that result is showing up at all, since its start node is deactivated in one of the snapshots.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @arifogel, @corinaminer, and @dhalperi)

___
*[jupyter_notebooks/Analyzing the Impact of Failures (and letting loose a Chaos Monkey).ipynb, line 225 at r2](https://reviewable.io/reviews/batfish/pybatfish/813#-MtoFDdu6SXPJHyzNInf:-Mtp6mKLD9FaYCS_BgPs:b-fc4um5) ([raw file](https://github.com/batfish/pybatfish/blob/8ab35cafad04f01c6ef9299af88548e24c167188/jupyter_notebooks/Analyzing%20the%20Impact%20of%20Failures%20(and%20letting%20loose%20a%20Chaos%20Monkey).ipynb#L225)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Looks like differential reachability is now including a flow starting on a node that is failed on the base snapshot. That's not something we want, is it? Can you look into why this is happening? Maybe the diff reach answerer has weird logic for picking start locations, or maybe forkSnapshot with `deactivate_nodes` isn't having the right effect.
</blockquote></details>

Due to bug fixed in batfish/batfish#7960

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/813)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
