### PR TITLE
Add routing nb

### PR DESCRIPTION
**Pull request by ratulm**
Waiting on selective notebook testing or BgpRouteConstraints making it to prod release.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[jupyter_notebooks/startup.py, line 15 at r1](https://reviewable.io/reviews/batfish/pybatfish/684#-MIfkA5RD9Z15QC_w7nQ:-MIfkA5RD9Z15QC_w7nR:byh89vz) ([raw file](https://github.com/batfish/pybatfish/blob/83ea035ffb16fb6980ac9e652f5e50d7a7f6f721/jupyter_notebooks/startup.py#L15)):*
> ```
> BgpRouteConstraints
> ```
I think this will still cause issues if running the notebooks vs old Pybf which doesn't have this construct

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[jupyter_notebooks/startup.py, line 15 at r1](https://reviewable.io/reviews/batfish/pybatfish/684#-MIfkA5RD9Z15QC_w7nQ:-MIfkYKl0_ee3u8IPIdA:b-90cg76) ([raw file](https://github.com/batfish/pybatfish/blob/83ea035ffb16fb6980ac9e652f5e50d7a7f6f721/jupyter_notebooks/startup.py#L15)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> BgpRouteConstraints
> ```
I think this will still cause issues if running the notebooks vs old Pybf which doesn't have this construct
</blockquote></details>

yeah, realized that committing. I'll import locally into the notebook (and debug the RTD formatting issue that victor spotted).

**Review by sfraint — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ratulm)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/684#-MIzVlBK1y1icG5A-sI0:-MIzVlBK1y1icG5A-sI1:b-6szr6q) (no related file):*
you should [update `test_notebook.py`](https://github.com/batfish/pybatfish/blob/master/tests/integration/test_notebook.py#L42) to skip testing this notebook for versions before it was released

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm)

___
*[jupyter_notebooks/Analyzing Routing Policies.ipynb, line 268 at r3](https://reviewable.io/reviews/batfish/pybatfish/684#-MIzxY42BVjbf_f18ZWq:-MIzxY43ERFRzYBC54Ww:biyld5v) ([raw file](https://github.com/batfish/pybatfish/blob/04d6ca2a0c089d264ca2ee7ac39adfbcc4570806/jupyter_notebooks/Analyzing Routing Policies.ipynb#L268)):*
> ```
> 10.0.0.0/8:8-32
> ```
I'm curious, is this a standard notation?
___
*[jupyter_notebooks/Analyzing Routing Policies.ipynb, line 928 at r3](https://reviewable.io/reviews/batfish/pybatfish/684#-MJ-8Zky-hrLDYIx7rrm:-MJ-8Zkz8Mf2Msi1rrj5:b93ex8r) ([raw file](https://github.com/batfish/pybatfish/blob/04d6ca2a0c089d264ca2ee7ac39adfbcc4570806/jupyter_notebooks/Analyzing Routing Policies.ipynb#L928)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>    "cell_type": "markdown",
>    "metadata": {},
>    "source": [
>     "    ### Current Status"
>    ]
> ```
</details>

this cell doesn't show up as markdown in the [github preview](https://github.com/batfish/pybatfish/blob/add-routing-nb/jupyter_notebooks/Analyzing%20Routing%20Policies.ipynb)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[jupyter_notebooks/Analyzing Routing Policies.ipynb, line 268 at r3](https://reviewable.io/reviews/batfish/pybatfish/684#-MIzxY42BVjbf_f18ZWq:-MJ-Ca235f6TvITyeCzI:bdsxpar) ([raw file](https://github.com/batfish/pybatfish/blob/04d6ca2a0c089d264ca2ee7ac39adfbcc4570806/jupyter_notebooks/Analyzing Routing Policies.ipynb#L268)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> 10.0.0.0/8:8-32
> ```
I'm curious, is this a standard notation?
</blockquote></details>

i think we made it up (a while ago) to represent prefix spaces.
___
*[jupyter_notebooks/Analyzing Routing Policies.ipynb, line 928 at r3](https://reviewable.io/reviews/batfish/pybatfish/684#-MJ-8Zky-hrLDYIx7rrm:-MJ-Cequ2pX8lIw2a1U0:b-g2k61f) ([raw file](https://github.com/batfish/pybatfish/blob/04d6ca2a0c089d264ca2ee7ac39adfbcc4570806/jupyter_notebooks/Analyzing Routing Policies.ipynb#L928)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>    "cell_type": "markdown",
>    "metadata": {},
>    "source": [
>     "    ### Current Status"
>    ]
> ```
this cell doesn't show up as markdown in the [github preview](https://github.com/batfish/pybatfish/blob/add-routing-nb/jupyter_notebooks/Analyzing%20Routing%20Policies.ipynb)
</blockquote></details>

ah, i had fixed that earlier. redid.

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/684)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
