### PR TITLE
Fix route assertions

### PR DESCRIPTION
**Pull request by ratulm**
Fixes https://github.com/batfish/batfish/issues/5863

Cc: @JulioPDX

### CODE REVIEW

**Comment by JulioPDX** [comment]
Awesome, thank you for the update!

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/859)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @ratulm)

___
*[`pybatfish/client/asserts.py` line 196 at r1](https://reviewable.io/reviews/batfish/pybatfish/859#-NCWsPGt7uHprKMYmxwp:-NCWsPGt7uHprKMYmxwq:be6el5) ([raw file](https://github.com/batfish/pybatfish/blob/c42b03c5a76fd272696d5e8735809e7ccbc41c14/pybatfish/client/asserts.py#L196)):*
> ```Python
>         d = d[vrf]
>     except KeyError:
>         raise BatfishAssertException("No VRF: {} on node {}".format(vrf, node))
> ```

Can we make these polymorphic? Aka, if it's a Mapping-like structure, assume it's n->v->[routes]. Then it won't be a breaking change.

Also, add type annotations ? :)



_Code quote:_
```Python
    try:
        d = routes[node]


    except KeyError:
        raise BatfishAssertException("No node: {}".format(node))

    try:
        d = d[vrf]
    except KeyError:
        raise BatfishAssertException("No VRF: {} on node {}".format(vrf, node))
```

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
