### PR TITLE
Port all WorkMgrV1 calls to WorkMgrV2 calls when available

### PR DESCRIPTION
**Pull request by arifogel**
- add version check on Session initialization to determine whether to
  use only v2 calls or use legacy v1 calls
- can force behavior without query by setting environment variable `pybf_use_deprecated_workmgr_v1` to `0` or `1`,
  or by passing `use_deprecated_workmgr_v1=True/False` to `Session.__init__`

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[`pybatfish/client/commands.py` line 51 at r2](https://reviewable.io/reviews/batfish/pybatfish/851#-N9EVyTG-HnYK1dh58lP:-N9EVyTG-HnYK1dh58lQ:b-liz7ng) ([raw file](https://github.com/batfish/pybatfish/blob/3837aed557f9b4697f08db17796ae79828621d83/pybatfish/client/commands.py#L51)):*
> ```Python
> # TODO: normally libraries don't configure logging in code
> _configure_default_logging()
> bf_session = Session(load_questions=False, use_deprecated_workmgr_v1=False)
> ```

Not sure whether we should force workmgr flag here. As is, importing bf_session now queries backend.
Perhaps we could use the env var if present, else default to a fixed value.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @dhalperi and @sfraint)

___
*[`pybatfish/client/commands.py` line 51 at r2](https://reviewable.io/reviews/batfish/pybatfish/851#-N9EVyTG-HnYK1dh58lP:-N9EX5lh-WPBqesGj2-1:b2to6du) ([raw file](https://github.com/batfish/pybatfish/blob/3837aed557f9b4697f08db17796ae79828621d83/pybatfish/client/commands.py#L51)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not sure whether we should force workmgr flag here. As is, importing bf_session now queries backend.
Perhaps we could use the env var if present, else default to a fixed value.


</blockquote></details>

To be clear, the current behavior for `bf_session` in this PR is to use env var if present, else query backend.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[`pybatfish/client/commands.py` line 51 at r2](https://reviewable.io/reviews/batfish/pybatfish/851#-N9EVyTG-HnYK1dh58lP:-N9IO5YnC8fHcs4FsdVp:bxc3n3f) ([raw file](https://github.com/batfish/pybatfish/blob/3837aed557f9b4697f08db17796ae79828621d83/pybatfish/client/commands.py#L51)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

To be clear, the current behavior for `bf_session` in this PR is to use env var if present, else query backend.
</blockquote></details>

solved by lazily querying whether to use v1 when not overridden

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/851#-N9I_Kz05WJXOH_Tex7-:-N9I_Kz05WJXOH_Tex70:b-bhti0z) (no related file):*
partially broke codecov for integration tests

___

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 8 of 12 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: all files reviewed, 8 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`.buildkite/pipeline.sh` line 103 at r5](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IP-0i6cPdkwsHaEx2:-N9IP-0i6cPdkwsHaEx3:b-q8fuqo) ([raw file](https://github.com/batfish/pybatfish/blob/abb2c96edd24eefe203a638e699f6084a87478ca/.buildkite/pipeline.sh#L103)):*
> ```Shell
> EOF
> done
> # test oldest python version using WorkMgrV1
> ```

Any particular reason to just use the oldest? Any reason not to just add it as a step in the above for loop over all version?



_Code quote:_
```Shell
# test oldest python version using WorkMgrV1
```
___
*[`pybatfish/client/restv2helper.py` line 637 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IXeVmBZmfatoi8HYq:-N9IXeVmBZmfatoi8HYr:boja01m) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/restv2helper.py#L637)):*
> ```Python
>     if query:
>         params[CoordConstsV2.QP_QUERY] = query
>     if max_suggestions:
> ```

Is `max_suggestions` == 0 ever valid/desired? We're not allowing that here.



_Code quote:_
```Python
    if max_suggestions:
        params[CoordConstsV2.QP_MAX_SUGGESTIONS] = max_suggestions
```
___
*[`pybatfish/client/restv2helper.py` line 738 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IYKl0DwUbzl8eeDeK:-N9IYKl0DwUbzl8eeDeL:b5ml3wy) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/restv2helper.py#L738)):*
> ```Python
>     session: "Session",
>     url_tail: str,
>     obj: Any,
> ```

Does `Any` include `None` or should this be `Optional[Any]` now?



_Code quote:_
```Python
Any
```
___
*[`pybatfish/client/session.py` line 1020 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Idc9M9KOyT8knN1l1:-N9Idc9M9KOyT8knN1l2:b1szn70) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/session.py#L1020)):*
> ```Python
>             )
>             return response
>         else:
> ```

nit: we usually just leave off the `else` and unindent this case (same comment in a few places, below)



_Code quote:_
```Python
        else:
            statuses = restv2helper.list_incomplete_work(self)
            return {CoordConsts.SVC_KEY_WORK_LIST: json.dumps(statuses)}
```
___
*[`pybatfish/client/session.py` line 1345 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IfBTg8BLyPZnD-SvX:-N9IfBTg8BLyPZnD-SvY:b5cmqnu) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/session.py#L1345)):*
> ```Python
>             return results
> 
>     def use_deprecated_workmgr_v1(self) -> bool:
> ```

Please add a docstring



_Code quote:_
```Python
    def use_deprecated_workmgr_v1(self) -> bool:
```
___
*[`pybatfish/client/workhelper.py` line 177 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IgSme0N7c1uqjb3Ut:-N9IgSme0N7c1uqjb3Uu:bxqyud8) ([raw file](https://github.com/batfish/pybatfish/blob/c8b54d862a764edefca761b25113d8503a9f1a05/pybatfish/client/workhelper.py#L177)):*
> ```Python
> 
> 
> def get_data_upload_question(session, question_name, question_json, parameters_json):
> ```

Is removing `parameters_json` related to migrating off of V1 APIs?



_Code quote:_
```Python
parameters_json
```
___
*[`pybatfish/client/workhelper.py` line 362 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Igkuo8fnf09sInkQZ:-N9Igkuo8fnf09sInkQ_:b70cip) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/workhelper.py#L362)):*
> ```Python
>         answer = restv2helper.get_work_status(session, w_item_id)
>         return {
>             CoordConsts.SVC_KEY_WORKSTATUS: answer[CoordConstsV2.PROP_WORK_STATUS_CODE],
> ```

Generally prefer `.get()` over `[]`



_Suggestion:_
```Python
            CoordConsts.SVC_KEY_WORKSTATUS: answer.get(CoordConstsV2.PROP_WORK_STATUS_CODE),
            CoordConsts.SVC_KEY_TASKSTATUS: json.dumps(answer.get(CoordConstsV2.PROP_TASK)),
```
___
*[`tests/client/test_commands.py` line 22 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IhW0S4dHBL8bEIdj-:-N9IhW0S4dHBL8bEIdj0:b-vthj9) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/tests/client/test_commands.py#L22)):*
> ```Python
> from pybatfish.client.session import _PYBF_USE_DEPRECATED_WORKMGR_V1_ENV
> 
> with patch.dict(os.environ, {_PYBF_USE_DEPRECATED_WORKMGR_V1_ENV: "0"}):
> ```

Maybe I just missed it, but what is this for?



_Code quote:_
```Python
with patch.dict(os.environ, {_PYBF_USE_DEPRECATED_WORKMGR_V1_ENV: "0"}):
```
___
*[`tests/client/test_session.py` line 98 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Ihzs965qO-mRZyqYq:-N9Ihzs965qO-mRZyqYr:bj7nkz9) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/tests/client/test_session.py#L98)):*
> ```Python
>         "pybatfish.client.restv2helper.get_component_versions"
>     ) as mock_get_component_versions:
>         mock_get_component_versions.return_value = {"Batfish": "1969.07.16"}
> ```

:rocket: :grin:

though I don't think we need to set a return value for a mock that isn't called



_Code quote:_
```Python
1969.07.16
```

**Comment by arifogel** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Ipgtz7U5LNEphrDkG:-N9Ipgtz7U5LNEphrDkH:ba2pr1b) (no related file):*
Adding a new batfish endpoint for getting api version. Will switch over once merged.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 14 of 21 files reviewed, 7 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Ipgtz7U5LNEphrDkG:-N9Jiq8K4crcGFS1uU7e:bkpr28s) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Adding a new batfish endpoint for getting api version. Will switch over once merged.
</blockquote></details>

After batfish/batfish#8465

___
___
*[`.buildkite/pipeline.sh` line 103 at r5](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IP-0i6cPdkwsHaEx2:-N9In8KD6WKbHZmTENuj:bscefi2) ([raw file](https://github.com/batfish/pybatfish/blob/abb2c96edd24eefe203a638e699f6084a87478ca/.buildkite/pipeline.sh#L103)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Any particular reason to just use the oldest? Any reason not to just add it as a step in the above for loop over all version?
</blockquote></details>

Was just trying to save some resources. We're going to remove this in the future anyway.
If you feel strongly, I'll add the other versions.
___
*[`pybatfish/client/restv2helper.py` line 637 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IXeVmBZmfatoi8HYq:-N9ImOTABRMAJb3yX-8i:br510jb) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/restv2helper.py#L637)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Is `max_suggestions` == 0 ever valid/desired? We're not allowing that here.
</blockquote></details>

I think we should just document that 0 is treated as no limit. And raise on negative numbers, which would cause a server-side exception.
I've made this change.
___
*[`pybatfish/client/restv2helper.py` line 738 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IYKl0DwUbzl8eeDeK:-N9IndRj-RX20QYKqeFX:b-lqtz8l) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/restv2helper.py#L738)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Does `Any` include `None` or should this be `Optional[Any]` now?
</blockquote></details>

`mypy` isn't complaining in the case where `None` is passed, so I think we're good.
___
*[`pybatfish/client/session.py` line 1020 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Idc9M9KOyT8knN1l1:-N9Jionm5IX5RnEfm8dY:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/session.py#L1020)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

nit: we usually just leave off the `else` and unindent this case (same comment in a few places, below)
</blockquote></details>

done
___
*[`pybatfish/client/session.py` line 1345 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IfBTg8BLyPZnD-SvX:-N9JalXl521OvAJq0Q8h:bb7f2mf) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/session.py#L1345)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Please add a docstring
</blockquote></details>

done
___
*[`pybatfish/client/workhelper.py` line 177 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IgSme0N7c1uqjb3Ut:-N9Intzn9ooCaU_UfhUM:b-bvrzzm) ([raw file](https://github.com/batfish/pybatfish/blob/c8b54d862a764edefca761b25113d8503a9f1a05/pybatfish/client/workhelper.py#L177)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Is removing `parameters_json` related to migrating off of V1 APIs?
</blockquote></details>

No, this was removed from v1 API in the backend years ago. The field has been ignored this whole time.
___
*[`pybatfish/client/workhelper.py` line 362 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Igkuo8fnf09sInkQZ:-N9Jb4lIBbOW95dBUBPd:be34yjd) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/workhelper.py#L362)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Generally prefer `.get()` over `[]`
</blockquote></details>

fixed here. leaving old usages as out of scope.
___
*[`tests/client/test_commands.py` line 22 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IhW0S4dHBL8bEIdj-:-N9Io7rdD21rzRFBD6AR:b9xshj) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/tests/client/test_commands.py#L22)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Maybe I just missed it, but what is this for?
</blockquote></details>

This prevents usages of `bf_session` from calling out to the server on import. But I've changed the implementation so that already doesn't happen until you call one of the new v2 apis.
Looks like the usage in this file didn't include new v2 API, so removed.
___
*[`tests/client/test_session.py` line 98 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Ihzs965qO-mRZyqYq:-N9IoUszEagnMy0Qmf04:b-a984db) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/tests/client/test_session.py#L98)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

:rocket: :grin:

though I don't think we need to set a return value for a mock that isn't called
</blockquote></details>

copypaste eror.
removed.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 14 of 21 files reviewed, 7 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/851#-N9Ipgtz7U5LNEphrDkG:-N9YO-yi5nLgAhQ_Cdmi:bkpr28u) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

After batfish/batfish#8465
</blockquote></details>

After batfish/batfish#8467

___

**Review by sfraint — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 7 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851#-:-N9bP15xAQc8uhMCP0uz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`.buildkite/pipeline.sh` line 103 at r5](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IP-0i6cPdkwsHaEx2:-N9bHSjxE4_AmwicBuiz:b3pmzy6) ([raw file](https://github.com/batfish/pybatfish/blob/abb2c96edd24eefe203a638e699f6084a87478ca/.buildkite/pipeline.sh#L103)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Was just trying to save some resources. We're going to remove this in the future anyway.
If you feel strongly, I'll add the other versions.
</blockquote></details>

I think it's fine as-is
___
*[`pybatfish/client/restv2helper.py` line 738 at r6](https://reviewable.io/reviews/batfish/pybatfish/851#-N9IYKl0DwUbzl8eeDeK:-N9bHnjP92pbYlnv-Nh8:b-tizpww) ([raw file](https://github.com/batfish/pybatfish/blob/263219cd108d1d7b9473b52245d731665c35f288/pybatfish/client/restv2helper.py#L738)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

`mypy` isn't complaining in the case where `None` is passed, so I think we're good.
</blockquote></details>

I meant more for the caller's sake, but still not a big deal
___
*[`pybatfish/client/restv2helper.py` line 487 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bJaMwCRhbsukAR1d_:-N9bJaMwCRhbsukAR1da:b-b7o3bq) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/restv2helper.py#L487)):*
> ```Python
> 
> 
> def get_api_version(session: "Session") -> str:
> ```

not really a question about this PR, but I'm curious - when is the API version incremented in the backend?



_Code quote:_
```Python
def get_api_version(session: "Session") -> str:
    """Gets the API version if present, else returns '2.0.0'"""
    component_versions = get_component_versions(session)
    return str(component_versions.get(CoordConsts.KEY_API_VERSION, "2.0.0"))
```
___
*[`pybatfish/client/session.py` line 1351 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bIfD06LllRvCs-ciz:-N9bIfD06LllRvCs-cj-:bnhs21q) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/session.py#L1351)):*
> ```Python
>         return self._use_deprecated_workmgr_v1
> 
>     def _should_use_deprecated_workmgr_v1(self) -> bool:
> ```

nit: if you're making more changes in this PR, how about `def _backend_only_supports_v1` or something like that? indicating this helper is all about what the backend supports



_Code quote:_
```Python
def _should_use_deprecated_workmgr_v1(self) -> bool:
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`pybatfish/client/restv2helper.py` line 487 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bJaMwCRhbsukAR1d_:-N9bnv_33i5xeVUgSe_e:b9fdnd8) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/restv2helper.py#L487)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

not really a question about this PR, but I'm curious - when is the API version incremented in the backend?
</blockquote></details>

It's semver. Major corresponds to new endpoint, e.g. /v3 instead of /v2. The minor version should be incremented whenever a new call is added. And I suppose we could increment patch version if we need to fix some CVE or something and the client needs to know it's been fixed. I wouldn't worry too much about patch version.
___
*[`pybatfish/client/session.py` line 1351 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bIfD06LllRvCs-ciz:-N9boluf1ndnwmdLnl_O:bi5u8vc) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/session.py#L1351)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

nit: if you're making more changes in this PR, how about `def _backend_only_supports_v1` or something like that? indicating this helper is all about what the backend supports
</blockquote></details>

Not convinced adding `backend` to the name makes things more clear or is even correct given the multiple ways of configuring the behavior.
However, updated the docstring here and in `__init__` to be more clear.

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`pybatfish/client/session.py` line 1351 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bIfD06LllRvCs-ciz:-N9c5CBm9t9NZWT2MZ7L:bia8nh0) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/session.py#L1351)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Not convinced adding `backend` to the name makes things more clear or is even correct given the multiple ways of configuring the behavior.
However, updated the docstring here and in `__init__` to be more clear.
</blockquote></details>

This helper function just queries the API version from the backend and returns a bool indicating if the backend supports the new v2 APIs, right? It is not using input from user/env/anywhere else.

I was thinking changing the helper function name would make that clearer.  Especially since `_should_use_deprecated_workmgr_v1`, `_use_deprecated_workmgr_v1` and `use_deprecated_workmgr_v1` are pretty ambiguous and not easy to distingush at a glance

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @dhalperi and @sfraint)

___
*[`pybatfish/client/session.py` line 1351 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bIfD06LllRvCs-ciz:-N9c83760SELMh1jmIvQ:bhafbq) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/session.py#L1351)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

This helper function just queries the API version from the backend and returns a bool indicating if the backend supports the new v2 APIs, right? It is not using input from user/env/anywhere else.

I was thinking changing the helper function name would make that clearer.  Especially since `_should_use_deprecated_workmgr_v1`, `_use_deprecated_workmgr_v1` and `use_deprecated_workmgr_v1` are pretty ambiguous and not easy to distingush at a glance
</blockquote></details>

How's this change?

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/851)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[`pybatfish/client/session.py` line 1351 at r9](https://reviewable.io/reviews/batfish/pybatfish/851#-N9bIfD06LllRvCs-ciz:-N9c8b4U1J7SvlAn_RGj:b-cufrwa) ([raw file](https://github.com/batfish/pybatfish/blob/76863f34384a7eed9ba167f2a07ab64c4d598237/pybatfish/client/session.py#L1351)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

How's this change?
</blockquote></details>

Looks good :thumbsup:

**Pull request merged**
