### PR TITLE
Fix tests after addition of NextHop column

### PR DESCRIPTION
**Pull request by arifogel**
- fixes following batfish/batfish#7838

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/797)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel)

*[a discussion](https://reviewable.io/reviews/batfish/pybatfish/797#-MrKgfe3A5iEi3thzcjg:-MrKgfe3A5iEi3thzcjh:b-xwdynt) (no related file):*
after batfish/batfish#7838

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/797)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/pybatfish/797)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
